default: &default
  adapter: postgresql
  reconnect: true
  pool: <%= Postal::Config.main_db.pool_size %>
  user: <%= Postal::Config.main_db.username %>
  password: <%= Postal::Config.main_db.password %>
  database: "<%= Postal::Config.main_db.database %>"

development:
  <<: *default

production:
  <<: *default

test:
  <<: *default
